from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from zipfile import ZipFile
from xml.etree import ElementTree as ET

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH


ROOT = Path(__file__).resolve().parents[1]

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
CP_NS = "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
DC_NS = "http://purl.org/dc/elements/1.1/"
EP_NS = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"

NS = {
    "w": W_NS,
    "cp": CP_NS,
    "dc": DC_NS,
    "ep": EP_NS,
}

HIDDEN_RISK_PATTERNS = [
    "python-docx",
    "generated by python-docx",
    "2013-12-23",
    "Microsoft Macintosh Word",
    "recommendation/figures",
    "_claude",
    "홍길동",
    "김철수",
    "placeholder",
    "TODO",
    "MISSING",
    "§",
]

STANDALONE_ABBREVIATION_PATTERNS = [
    (re.compile(r"\bAI\b"), "standalone AI; write it out or avoid the abbreviation"),
]


@dataclass
class Verification:
    passes: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    failures: list[str] = field(default_factory=list)

    def ok(self, message: str) -> None:
        self.passes.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    def fail(self, message: str) -> None:
        self.failures.append(message)

    @property
    def passed(self) -> bool:
        return not self.failures


def qn(local: str) -> str:
    return f"{{{W_NS}}}{local}"


def text_of(root: ET.Element, path: str) -> str:
    elem = root.find(path, NS)
    return "" if elem is None or elem.text is None else elem.text


def check_file_exists(v: Verification, path: Path, label: str) -> None:
    if path.exists():
        v.ok(f"{label} exists: {path}")
    else:
        v.fail(f"{label} missing: {path}")


def check_markdown(v: Verification, md_path: Path, stem: str) -> None:
    if not md_path.exists():
        v.fail(f"markdown missing: {md_path}")
        return

    text = md_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    rev_match = re.search(r"full_paper_rev(\d{3})_codex", stem)
    expected_fig_dir = f"figures/full_paper_rev{rev_match.group(1)}" if rev_match else None

    if lines and lines[0].startswith("# "):
        v.ok("markdown title line exists")
    else:
        v.fail("markdown title line must start with '# '")

    if "**Abstract**" in text:
        v.ok("markdown Abstract heading is bold")
    else:
        v.fail("markdown Abstract heading missing or not bold")

    if "## References" in text:
        v.ok("markdown References section exists")
    else:
        v.fail("markdown References section missing")

    if expected_fig_dir and expected_fig_dir in text:
        v.ok(f"markdown uses current figure folder: {expected_fig_dir}")
    elif expected_fig_dir:
        v.fail(f"markdown does not use current figure folder: {expected_fig_dir}")

    stale_fig_dirs = sorted(set(re.findall(r"figures/full_paper_rev\d{3}", text)))
    if expected_fig_dir:
        stale_fig_dirs = [d for d in stale_fig_dirs if d != expected_fig_dir]
    if stale_fig_dirs:
        v.fail(f"markdown has stale figure folders: {', '.join(stale_fig_dirs)}")
    else:
        v.ok("markdown has no stale figure folders")

    for pattern in HIDDEN_RISK_PATTERNS:
        if pattern in text:
            v.fail(f"markdown contains risk pattern: {pattern}")
    v.ok("markdown risk-pattern scan complete")

    main_text = text.split("## References", 1)[0]
    abbreviation_hits: list[str] = []
    for pattern, description in STANDALONE_ABBREVIATION_PATTERNS:
        for match in pattern.finditer(main_text):
            line_no = text.count("\n", 0, match.start()) + 1
            abbreviation_hits.append(f"line {line_no}: {description}")
    if abbreviation_hits:
        v.fail("markdown standalone abbreviation risk: " + "; ".join(abbreviation_hits[:5]))
    else:
        v.ok("markdown standalone abbreviation scan passed")

    figure_refs = re.findall(r"^!\[[^\]]*\]\(([^)]+)\)", text, flags=re.M)
    if 2 <= len(figure_refs) <= 6:
        v.ok(f"markdown has figure references within expected range: {len(figure_refs)}")
    else:
        v.fail(f"markdown figure reference count is {len(figure_refs)}, expected 2-6")
    for ref in figure_refs:
        path = ROOT / ref
        if path.exists():
            v.ok(f"figure file exists: {ref}")
        else:
            v.fail(f"figure file missing: {ref}")

    table_captions = re.findall(r"^Table \d+\.", text, flags=re.M)
    if 3 <= len(table_captions) <= 4:
        v.ok(f"markdown has table captions within expected range: {len(table_captions)}")
    else:
        v.fail(f"markdown table caption count is {len(table_captions)}, expected 3-4")

    before_refs = text.split("## References", 1)[0]
    body_cites = sorted(set(int(x) for x in re.findall(r"\[(\d+)\]", before_refs)))
    refs = sorted(set(int(x) for x in re.findall(r"^\[(\d+)\]", text, flags=re.M)))
    if body_cites == refs and refs:
        v.ok(f"citations match references: {body_cites}")
    else:
        v.fail(f"citation/reference mismatch: body={body_cites}, refs={refs}")


def check_docx_xml(v: Verification, docx_path: Path) -> None:
    if not docx_path.exists():
        v.fail(f"DOCX missing: {docx_path}")
        return

    with ZipFile(docx_path) as zf:
        names = set(zf.namelist())
        xml_names = [name for name in names if name.endswith((".xml", ".rels"))]
        hits: list[str] = []
        for name in xml_names:
            data = zf.read(name).decode("utf-8", errors="ignore")
            for pattern in HIDDEN_RISK_PATTERNS:
                if pattern in data:
                    hits.append(f"{name}: {pattern}")
        if hits:
            v.fail("DOCX hidden XML risk patterns found: " + "; ".join(hits))
        else:
            v.ok("DOCX hidden XML risk-pattern scan passed")

        for forbidden in [
            "word/comments.xml",
            "word/footnotes.xml",
            "word/endnotes.xml",
            "docProps/custom.xml",
        ]:
            if forbidden in names:
                v.fail(f"unexpected DOCX part exists: {forbidden}")
            else:
                v.ok(f"unexpected DOCX part absent: {forbidden}")

        embeddings = [name for name in names if name.startswith("word/embeddings/")]
        if embeddings:
            v.fail("DOCX contains embedded objects: " + ", ".join(sorted(embeddings)))
        else:
            v.ok("DOCX contains no embedded objects")

        media = [name for name in names if name.startswith("word/media/")]
        if 2 <= len(media) <= 6:
            v.ok(f"DOCX embedded media count is within expected range: {len(media)}")
        else:
            v.fail(f"DOCX media count is {len(media)}, expected 2-6")

        core = ET.fromstring(zf.read("docProps/core.xml"))
        creator = text_of(core, "dc:creator")
        description = text_of(core, "dc:description")
        title = text_of(core, "dc:title")
        if title:
            v.ok("DOCX core title is set")
        else:
            v.fail("DOCX core title is empty")
        if creator and creator != "python-docx":
            v.ok(f"DOCX core creator is set: {creator}")
        else:
            v.fail(f"DOCX core creator is unsafe: {creator!r}")
        if description and "python-docx" not in description:
            v.ok("DOCX core description is submission-specific")
        else:
            v.fail("DOCX core description is missing or generator-like")

        app = ET.fromstring(zf.read("docProps/app.xml"))
        app_name = text_of(app, "ep:Application")
        company = text_of(app, "ep:Company")
        pages = text_of(app, "ep:Pages")
        words = text_of(app, "ep:Words")
        if app_name == "Microsoft Word":
            v.ok("DOCX app Application is Microsoft Word")
        else:
            v.fail(f"DOCX app Application is {app_name!r}")
        if company == "Samsung Electronics":
            v.ok("DOCX app Company is Samsung Electronics")
        else:
            v.fail(f"DOCX app Company is {company!r}")
        try:
            page_count = int(pages)
        except (TypeError, ValueError):
            v.fail(f"DOCX app Pages is unsafe: {pages!r}")
        else:
            if 4 <= page_count <= 10:
                v.ok(f"DOCX app Pages is within full-paper limit: {page_count}")
            else:
                v.fail(f"DOCX app Pages is {page_count}, expected 4-10")
        if words and words != "0":
            v.ok(f"DOCX app Words is nonzero: {words}")
        else:
            v.fail(f"DOCX app Words is unsafe: {words!r}")

        document = ET.fromstring(zf.read("word/document.xml"))
        document_xml = zf.read("word/document.xml").decode("utf-8", errors="ignore")
        figure_caption_count = len(re.findall(r"Figure \d+\.", document_xml))
        if 2 <= figure_caption_count <= 6:
            v.ok(f"DOCX figure caption count is within expected range: {figure_caption_count}")
        else:
            v.fail(f"DOCX figure caption count is {figure_caption_count}, expected 2-6")
        table_caption_count = len(re.findall(r"Table \d+\.", document_xml))
        if 3 <= table_caption_count <= 4:
            v.ok(f"DOCX has table captions within expected range: {table_caption_count}")
        else:
            v.fail(f"DOCX table caption count is {table_caption_count}, expected 3-4")

        headers = "".join(
            zf.read(name).decode("utf-8", errors="ignore")
            for name in names
            if name.startswith("word/header")
        )
        footers = "".join(
            zf.read(name).decode("utf-8", errors="ignore")
            for name in names
            if name.startswith("word/footer")
        )
        if "Samsung Best Paper Awards" in headers:
            v.ok("DOCX header contains Samsung Best Paper Awards")
        else:
            v.fail("DOCX header text missing")
        if "Samsung Electronics" in footers:
            v.ok("DOCX footer contains affiliation company")
        else:
            v.fail("DOCX first-page affiliation footer missing company")

        check_sections(v, document)
        check_table_borders(v, document)
        check_font_mappings(v, document)


def check_sections(v: Verification, document: ET.Element) -> None:
    sects = document.findall(".//w:sectPr", NS)
    if len(sects) == 2:
        v.ok("DOCX has 2 sections")
    else:
        v.fail(f"DOCX section count is {len(sects)}, expected 2")

    for idx, sect in enumerate(sects, start=1):
        pg_size = sect.find("w:pgSz", NS)
        margins = sect.find("w:pgMar", NS)
        cols = sect.find("w:cols", NS)
        if pg_size is None:
            v.fail(f"section {idx} page size missing")
            continue
        width = pg_size.attrib.get(qn("w"))
        height = pg_size.attrib.get(qn("h"))
        if (width, height) == ("11906", "16838"):
            v.ok(f"section {idx} A4 page size")
        else:
            v.fail(f"section {idx} page size is {(width, height)}, expected A4 twips")
        if margins is None:
            v.fail(f"section {idx} margins missing")
            continue
        expected = {
            "top": "850",
            "right": "850",
            "bottom": "850",
            "left": "850",
            "header": "567",
            "footer": "283",
        }
        actual = {key: margins.attrib.get(qn(key)) for key in expected}
        if actual == expected:
            v.ok(f"section {idx} margins/header/footer match rules")
        else:
            v.fail(f"section {idx} margin mismatch: {actual}")
        if idx == 2:
            if cols is not None and cols.attrib.get(qn("num")) == "2" and cols.attrib.get(qn("space")) == "283":
                v.ok("body section has 2 columns with 0.5 cm gap")
            else:
                v.fail("body section column settings do not match 2 columns / 0.5 cm")


def edge_values(row: ET.Element, edge: str) -> list[tuple[str | None, str | None]]:
    values: list[tuple[str | None, str | None]] = []
    for cell in row.findall("w:tc", NS):
        border = cell.find(f"w:tcPr/w:tcBorders/w:{edge}", NS)
        if border is None:
            values.append((None, None))
        else:
            values.append((border.attrib.get(qn("val")), border.attrib.get(qn("sz"))))
    return values


def all_edge(values: list[tuple[str | None, str | None]], val: str, size: str | None = None) -> bool:
    if not values:
        return False
    for actual_val, actual_size in values:
        if actual_val != val:
            return False
        if size is not None and actual_size != size:
            return False
    return True


def check_table_borders(v: Verification, document: ET.Element) -> None:
    tables = document.findall(".//w:tbl", NS)
    if not (3 <= len(tables) <= 4):
        v.fail(f"DOCX table count is {len(tables)}, expected 3-4")
        return
    v.ok(f"DOCX has tables within expected range: {len(tables)}")

    for idx, table in enumerate(tables, start=1):
        rows = table.findall("w:tr", NS)
        if not rows:
            v.fail(f"table {idx} has no rows")
            continue
        first = rows[0]
        last = rows[-1]
        if all_edge(edge_values(first, "top"), "single", "12"):
            v.ok(f"table {idx} top rule is bold")
        else:
            v.fail(f"table {idx} top rule mismatch")
        if all_edge(edge_values(first, "bottom"), "single", "8"):
            v.ok(f"table {idx} header bottom rule exists")
        else:
            v.fail(f"table {idx} header bottom rule mismatch")
        if all_edge(edge_values(last, "bottom"), "single", "12"):
            v.ok(f"table {idx} bottom rule is bold")
        else:
            v.fail(f"table {idx} bottom rule mismatch")
        if all_edge(edge_values(first, "left"), "nil") and all_edge(edge_values(first, "right"), "nil"):
            v.ok(f"table {idx} has no vertical outside rules on header row")
        else:
            v.fail(f"table {idx} vertical rule mismatch")


def check_font_mappings(v: Verification, document: ET.Element) -> None:
    font_nodes = document.findall(".//w:rFonts", NS)
    if not font_nodes:
        v.fail("DOCX has no explicit run font mappings")
        return

    bad: list[str] = []
    for node in font_nodes:
        ascii_font = node.attrib.get(qn("ascii"))
        hansi_font = node.attrib.get(qn("hAnsi"))
        east_asia_font = node.attrib.get(qn("eastAsia"))
        if ascii_font != "Times New Roman" or hansi_font != "Times New Roman" or east_asia_font != "바탕체":
            bad.append(f"ascii={ascii_font}, hAnsi={hansi_font}, eastAsia={east_asia_font}")

    if bad:
        v.fail("DOCX run font mapping mismatch: " + "; ".join(bad[:5]))
    else:
        v.ok(f"DOCX run font mappings match Times New Roman / 바탕체: {len(font_nodes)} runs")


def first_run(paragraph):
    for run in paragraph.runs:
        if run.text.strip():
            return run
    return None


def check_docx_runs(v: Verification, docx_path: Path) -> None:
    if not docx_path.exists():
        return
    doc = Document(docx_path)
    paragraphs = [p for p in doc.paragraphs if p.text.strip()]
    if len(paragraphs) < 5:
        v.fail("DOCX has too few non-empty paragraphs")
        return

    expected_first = [
        ("title", paragraphs[0], 20.0, True),
        ("author", paragraphs[1], 12.0, True),
        ("Abstract heading", paragraphs[2], 10.0, True),
        ("Abstract body", paragraphs[3], 10.0, True),
    ]
    for label, paragraph, size, bold in expected_first:
        run = first_run(paragraph)
        if run is None:
            v.fail(f"{label} run missing")
            continue
        actual_size = run.font.size.pt if run.font.size else None
        if actual_size == size and run.bold is bold:
            v.ok(f"{label} font matches: {size} pt bold={bold}")
        else:
            v.fail(f"{label} font mismatch: size={actual_size}, bold={run.bold}")

    expected_alignment = [
        ("title", paragraphs[0], WD_ALIGN_PARAGRAPH.LEFT),
        ("author", paragraphs[1], WD_ALIGN_PARAGRAPH.LEFT),
        ("Abstract heading", paragraphs[2], WD_ALIGN_PARAGRAPH.LEFT),
        ("Abstract body", paragraphs[3], WD_ALIGN_PARAGRAPH.JUSTIFY),
        ("keywords", paragraphs[4], WD_ALIGN_PARAGRAPH.LEFT),
    ]
    for label, paragraph, expected in expected_alignment:
        if paragraph.alignment == expected:
            v.ok(f"{label} alignment matches rule")
        else:
            v.fail(f"{label} alignment mismatch: {paragraph.alignment} != {expected}")

    line_spacing_failures = [
        (idx, p.text[:60], p.paragraph_format.line_spacing)
        for idx, p in enumerate(paragraphs)
        if p.paragraph_format.line_spacing != 1.0
    ]
    if line_spacing_failures:
        details = "; ".join(f"{idx}:{spacing}:{text}" for idx, text, spacing in line_spacing_failures[:5])
        v.fail("paragraph line spacing is not 1.0: " + details)
    else:
        v.ok("all non-empty top-level paragraphs use line spacing 1.0")

    section_count = 0
    subsection_count = 0
    caption_count = 0
    justified_body_count = 0
    body_alignment_failures: list[str] = []
    for paragraph_index, paragraph in enumerate(paragraphs):
        text = paragraph.text.strip()
        run = first_run(paragraph)
        if run is None:
            continue
        size = run.font.size.pt if run.font.size else None
        if re.match(r"^\d+\. [A-Za-z]", text):
            section_count += 1
            if size != 12.0 or run.bold is not True:
                v.fail(f"section heading font mismatch: {text}")
        elif re.match(r"^\d+\.\d+\. ", text):
            subsection_count += 1
            if size != 10.0 or run.bold is not True:
                v.fail(f"subsection heading font mismatch: {text}")
        elif re.match(r"^(Figure|Table) \d+\. ", text):
            caption_count += 1
            if size != 9.0:
                v.fail(f"caption font size mismatch: {text}")
        elif (
            paragraph_index >= 5
            and text != "References"
            and not text.startswith("[")
            and not text.startswith("Keywords:")
        ):
            if paragraph.alignment == WD_ALIGN_PARAGRAPH.JUSTIFY:
                justified_body_count += 1
            else:
                body_alignment_failures.append(text[:60])
    if section_count >= 3:
        v.ok(f"section headings checked: {section_count}")
    else:
        v.fail(f"too few section headings found: {section_count}")
    if subsection_count >= 8:
        v.ok(f"subsection headings checked: {subsection_count}")
    else:
        v.warn(f"subsection heading count is {subsection_count}")
    if 5 <= caption_count <= 10:
        v.ok(f"caption paragraphs checked: {caption_count}")
    else:
        v.fail(f"caption paragraph count is {caption_count}, expected 5-10")

    if body_alignment_failures:
        v.fail("body paragraph alignment is not justified: " + "; ".join(body_alignment_failures[:5]))
    elif justified_body_count >= 20:
        v.ok(f"body paragraphs are justified: {justified_body_count}")
    else:
        v.fail(f"too few justified body paragraphs found: {justified_body_count}")

    check_references(v, paragraphs)


def check_references(v: Verification, paragraphs) -> None:
    references = [p for p in paragraphs if re.match(r"^\[\d+\]", p.text.strip())]
    if 7 <= len(references) <= 20:
        v.ok(f"reference paragraph count is within current full-paper range: {len(references)}")
    else:
        v.fail(f"reference paragraph count is {len(references)}, expected 7-20")

    italic_refs = 0
    bold_volume_refs = 0
    bad_runs: list[str] = []
    raw_markdown_refs: list[str] = []
    publication_title_case_failures: list[str] = []
    lowercase_title_words = {"of", "the", "on", "and", "in"}
    for paragraph in references:
        text = paragraph.text.strip()
        if "*" in text:
            raw_markdown_refs.append(text[:60])
        has_italic = False
        has_bold = False
        italic_text_parts: list[str] = []
        for run in paragraph.runs:
            if not run.text.strip():
                continue
            size = run.font.size.pt if run.font.size else None
            if size != 10.0:
                bad_runs.append(f"{text[:30]} size={size}")
            if run.font.name != "Times New Roman":
                bad_runs.append(f"{text[:30]} font={run.font.name}")
            has_italic = has_italic or run.italic is True
            has_bold = has_bold or run.bold is True
            if run.italic is True:
                italic_text_parts.append(run.text)
        if has_italic:
            italic_refs += 1
            italic_text = "".join(italic_text_parts)
            words = re.findall(r"[A-Za-z]+", italic_text)
            bad_words = [word for word in words if word in lowercase_title_words]
            if bad_words:
                publication_title_case_failures.append(f"{text[:30]}: {', '.join(sorted(set(bad_words)))}")
        if has_bold:
            bold_volume_refs += 1

    if raw_markdown_refs:
        v.fail("reference paragraphs contain raw markdown markers: " + "; ".join(raw_markdown_refs[:3]))
    else:
        v.ok("reference paragraphs contain no raw markdown emphasis markers")
    if bad_runs:
        v.fail("reference run formatting mismatch: " + "; ".join(bad_runs[:5]))
    else:
        v.ok("reference runs use 10 pt Times New Roman")
    if italic_refs == len(references) and references:
        v.ok("all references include italic publication title runs")
    else:
        v.fail(f"references with italic publication title runs: {italic_refs}/{len(references)}")
    if publication_title_case_failures:
        v.fail("reference publication title casing mismatch: " + "; ".join(publication_title_case_failures[:5]))
    else:
        v.ok("reference publication titles use strict title case")
    if bold_volume_refs >= 1:
        v.ok("at least one journal volume run is bold")
    else:
        v.fail("no bold journal volume run found")


def check_pdf(v: Verification, pdf_path: Path) -> None:
    if not pdf_path.exists():
        v.fail(f"PDF missing: {pdf_path}")
        return
    try:
        import fitz
    except ImportError:
        v.warn("PyMuPDF is not installed; PDF checks skipped")
        return

    doc = fitz.open(pdf_path)
    if 4 <= len(doc) <= 10:
        v.ok(f"PDF page count is within full-paper limit: {len(doc)}")
    else:
        v.fail(f"PDF page count is {len(doc)}, expected 4-10")
    first_page_text = doc[0].get_text("text")
    lines = [line.strip() for line in first_page_text.splitlines()]
    nonempty_lines = [line for line in lines if line]
    if any(line.startswith("Samsung Best Paper Awards") for line in nonempty_lines[:5]):
        v.ok("PDF first page visibly contains Samsung Best Paper Awards header")
    else:
        v.fail("PDF first page header text not visible in extracted text")
    if any("Samsung Electronics" in line and "QIE" in line for line in nonempty_lines[:8]):
        v.ok("PDF first page visibly contains affiliation footer")
    else:
        v.fail("PDF first page affiliation footer not visible in extracted text")
    if any(line == "1" for line in nonempty_lines[:8]):
        v.ok("PDF first page visibly contains page number")
    else:
        v.fail("PDF first page page number not visible in extracted text")

    try:
        abstract_start = next(i for i, line in enumerate(lines) if line == "Abstract")
        author_index = next(i for i, line in enumerate(lines) if line.startswith("최호길"))
        title_lines = [
            line
            for line in lines[:author_index]
            if line
            and not line.startswith("Samsung Best Paper Awards")
            and "Samsung Electronics" not in line
            and line != "1"
        ]
        if 1 <= len(title_lines) <= 2:
            v.ok(f"PDF title line count is within 2-line limit: {len(title_lines)}")
        else:
            v.fail(f"PDF title line count is {len(title_lines)}, expected 1-2")
        keywords = next(i for i, line in enumerate(lines) if line.startswith("Keywords:"))
        abstract_lines = [line for line in lines[abstract_start + 1 : keywords] if line]
        if len(abstract_lines) <= 15:
            v.ok(f"PDF abstract line count is {len(abstract_lines)}")
        else:
            v.fail(f"PDF abstract line count is {len(abstract_lines)}, expected <=15")
    except StopIteration:
        v.fail("PDF title/author/Abstract-to-Keywords range not found")


def check_render_folder(v: Verification, stem: str) -> None:
    render_stem = stem.removesuffix("_codex")
    render_dir = ROOT / "tmp" / "docs" / f"{render_stem}_pages"
    if not render_dir.exists():
        v.warn(f"render folder missing: {render_dir}")
        return
    pages = sorted(render_dir.glob("page_*.png"))
    sheet = render_dir / "contact_sheet.png"
    expected_pages = None
    pdf_path = ROOT / f"{stem}.pdf"
    if pdf_path.exists():
        try:
            import fitz

            with fitz.open(pdf_path) as doc:
                expected_pages = len(doc)
        except ImportError:
            expected_pages = None
    if expected_pages is not None and len(pages) == expected_pages and sheet.exists():
        v.ok(f"render folder contains {expected_pages} page PNGs and contact sheet")
    elif expected_pages is None and 4 <= len(pages) <= 10 and sheet.exists():
        v.ok(f"render folder contains page PNGs within full-paper limit: {len(pages)}")
    else:
        expected = f", expected_pages={expected_pages}" if expected_pages is not None else ""
        v.fail(f"render folder incomplete: pages={len(pages)}, contact_sheet={sheet.exists()}{expected}")


def render_report(v: Verification, stem: str) -> str:
    status = "PASS" if v.passed else "FAIL"
    lines = [
        f"# {stem} verification report",
        "",
        f"Status: {status}",
        "",
        f"Passes: {len(v.passes)}",
        f"Warnings: {len(v.warnings)}",
        f"Failures: {len(v.failures)}",
        "",
    ]
    if v.failures:
        lines.append("## Failures")
        lines.extend(f"- {item}" for item in v.failures)
        lines.append("")
    if v.warnings:
        lines.append("## Warnings")
        lines.extend(f"- {item}" for item in v.warnings)
        lines.append("")
    lines.append("## Passed Checks")
    lines.extend(f"- {item}" for item in v.passes)
    lines.append("")
    return "\n".join(lines)


def verify(stem: str) -> Verification:
    v = Verification()
    md_path = ROOT / f"{stem}.md"
    docx_path = ROOT / f"{stem}.docx"
    pdf_path = ROOT / f"{stem}.pdf"

    check_file_exists(v, md_path, "markdown")
    check_file_exists(v, docx_path, "DOCX")
    check_file_exists(v, pdf_path, "PDF")
    check_markdown(v, md_path, stem)
    check_docx_xml(v, docx_path)
    check_docx_runs(v, docx_path)
    check_pdf(v, pdf_path)
    check_render_folder(v, stem)
    return v


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify a Samsung full-paper package.")
    parser.add_argument("stem", help="Artifact stem, e.g. full_paper_rev015_codex")
    parser.add_argument("--report", help="Optional markdown report path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    verification = verify(args.stem)
    report = render_report(verification, args.stem)
    print(report)
    if args.report:
        report_path = Path(args.report)
        if not report_path.is_absolute():
            report_path = ROOT / report_path
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(report, encoding="utf-8")
    return 0 if verification.passed else 1


if __name__ == "__main__":
    sys.exit(main())
